[package]
name = "house-price-predictor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
polars = { version = "0.38.0", features = ["csv"] }
rand = "0.9.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
xgboost = "0.1.4"
